spring:
  application:
    name: AUTH-SERVICE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_app_auth_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8086

#To make this user service register with eureka server
#we need to provide eureka server url
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

secret:
    key: a2fc70d8032e3945874204f478af88abe5a08eb185c95f005a206dbec19d9261