spring:
  application:
    name: SERVICE-REGISTRY


#Eureka server runs on port number 8761 like mysql, postgres
server:
  port: 8761


#By default, every eureka server is client and server so to make it is not a client or to make it as a server
#we need to disable these below two properties of the eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false