spring:
#  config:
#    import: C:\Users\jayar\Desktop\test.yaml
#  main:
#    allow-bean-definition-overriding: true

  application:
    name: USER-SERVICE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_app_users_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081

#To make this user service register with eureka server
#we need to provide eureka server url
# Corrected Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


#debug: true

simple:
  message: TESTING

employee:
     name: Jaya Ram

manager:
     age: 25








