spring:
  application:
    name: ORDER-SERVICE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_app_orders_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9093
    # Producer Configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/jairam1
server:
  port: 8082

#To make this user service register with eureka server
#we need to provide eureka server url
# Corrected Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

user:
  service:
    url: http://localhost:8081/api/users

address:
  service:
    url: http://localhost:8084/api/address

product:
  service:
    url: http://localhost:8083/api/products

#logging:
#  level:
#    com.codewave.orderservice.client: ERROR