spring:
  application:
    name: ANALYTICS-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_app_analytics_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9093
    # Consumer Configuration
    consumer:
      group-id: analytics-service-group  # ← Important: unique for analytics service
      auto-offset-reset: earliest  # Read from beginning if no offset exists
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
server:
  port: 8085

#To make this user service register with eureka server
#we need to provide eureka server url
# Corrected Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

